/*
 * WAIT.ASM
 *
 *  CREATED: 2017/10/3
 *  AUTHOR: SHAOHUI Z5155945
 */ 
;----------------------------------
;SOME FUNCTIONS TO GENERATE DELAYS
;WAIT_1MS
;WAIT_MORE
;----------------------------------

;FUNCTION TO WAIT FOR 1MS
WAIT_1MS:
	PUSH R24
	PUSH R25

	LDI R24, LOW(4100)
	LDI R25, HIGH(4100)		;A LITTLE MORE THAN 1MS
	MS_LOOP:
		SBIW R24, 1
		BRNE MS_LOOP
	
	POP R25
	POP R24
	RET

;USING R16 AS INPUT FOR WAIT R16MS
WAIT_MORE:
	PUSH R16

	WAIT_MORE_LOOP:
		RCALL WAIT_1MS		;EACH TIME WAIT FOR 1MS
		DEC R16
		BRNE WAIT_MORE_LOOP

	POP R16
	RET
